### ISSUE TITLE
document how to use custom css with chroma

### ISSUE THREAD

**Issue by helmbold** [sergiandreplace/sergiandreplace.com#5]
It should be documented (on the [Syntax Highlighting](https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css) page) that the following parameters must be added to the config in order to enable custom css for the syntax highlighter:

```
pygmentsUseClasses=true

[params.customCSS]
url = "/syntax.css"
```

And maybe it should be mentioned that the css file must be placed in the `static` directory.

**Comment by sergiandreplace** [comment]
I didn't see your comment until now... that I was precisely trying to fix this!

Thanks for the tip!
